@startuml
' style tweaks to make the diagram a little more readable
skinparam {
  Style StrictUML
  RoundCorner 5
  ParticipantPadding 10
  Padding 2
  defaultFontSize 14
  SequenceStereotype {
    Font {
      Size 12
      Style plain
    }
  }
  Database {
    ' the default border does not match the normal colors (bug?), so fix this
    BorderColor #A80036
  }
}
actor User as user
participant ":Main" as main
participant ":MainMenu" as menu << frame >>
participant ":ProductViewer" as viewer << dialog >>
participant "dao\n:ProductJdbiDAO" as dao <<Product DAO >>
participant "categoryModel\n:SimpleListModel" as model
participant "product\n:Product" as product << domain >>
database "H2\nDatabase" as db

create dao
main -> dao : «construct»


create menu
main -> menu : «construct(dao)»

user -> menu++ : clicks 'View Products'

create viewer
menu -> viewer++ : « construct (dao)»

dialog -> dao : getProducts()
dao++
dao -> db++ : SELECT * FROM PRODUCT ORDER BY PRODUCT_ID
return query result
return products

create model

viewer -> model : <<construct>>
viewer -> model++ : updateItems(products)
model--

user <-- viewer : displays products
viewer--
user -> viewer++ : Clicks a Category
viewer -> dao++ : dao.filterByCategory((String)categoryComboBox.getSelectedItem())

database "H2\nDatabase" as db
dao -> db++ : "SELECT * FROM PRODUCT WHERE PRODUCT_CATEGORY = :category"
return query result
return categories
db--
dao--
viewer -> model++ :productsModel.updateItems(product)
model--
viewer -> viewer : productsList.setModel(productsModel)
viewer -> viewer : dispose()
viewer --> menu
destroy viewer
@enduml
